package pro.sky.telegrambot.constants;

public enum AdopterStatus {

    DEFAULT,
    WAITING_FOR_ADOPTER_FIRST_NAME,
    WAITING_FOR_ADOPTER_LAST_NAME,
    WAITING_FOR_ADOPTER_PASSPORT,
    WAITING_FOR_ADOPTER_AGE,
    WAITING_FOR_ADOPTER_PHONE,
    WAITING_FOR_ADOPTER_EMAIL,
    WAITING_FOR_ADOPTER_PET


}
